name: run test
on: push

jobs:
  run-test: 
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Setup RhinoCompute
        run: ../../../compute.geometry/compute.geometry.exe
      - run: dotnet test

