name: Run Unit Test
on: push

jobs:
  run-test: 
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Setup RhinoCompute
        run: |
          Start-Process -FilePath ../../../compute.geometry/compute.geometry.exe
          Start-Sleep -Seconds 5
      - name: Run Unit Test
        run: dotnet test

